version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://chronotrail:password@db:5432/chronotrail
      - OPENSEARCH_URL=http://opensearch:9200
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
      - S3_BUCKET_NAME=chronotrail-media
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key}
      - ENVIRONMENT=development
    depends_on:
      - db
      - opensearch
      - localstack
    volumes:
      - ./logs:/app/logs
    networks:
      - chronotrail-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=chronotrail
      - POSTGRES_USER=chronotrail
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - chronotrail-network

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - cluster.name=chronotrail-cluster
      - node.name=chronotrail-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - chronotrail-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
    networks:
      - chronotrail-network

  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - DEBUG=1
      - SERVICES=s3,bedrock,textract,transcribe,rekognition,cognito-idp
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/tmp/localstack"
    networks:
      - chronotrail-network

volumes:
  postgres_data:
  opensearch_data:

networks:
  chronotrail-network:
    driver: bridge